// src/database/seeds/initialCustomers.ts
import { Customer } from '../models/Customer';

export const initialCustomers: Customer[] = [
  {
    id: 'CUST001',
    name_en: 'Alpha Supplies',
    name_ar: 'ألفا للمستلزمات',
    vat_number: '1000000001',
    cr_number: '20000001',
    contact_person: 'John Doe',
    phone_number: '+966500000001',
    email: 'john.doe@alphasupplies.com',
    route_days: 'Monday',
    building_en: 'Building A',
    building_ar: null,
    secondary_en: 'Suite 101',
    secondary_ar: null,
    street_en: 'King Fahd Road',
    street_ar: null,
    district_en: 'Al Olaya',
    district_ar: null,
    city_en: 'Riyadh',
    city_ar: 'الرياض',
    postal_en: '10001',
    postal_ar: null
  },
  {
    id: 'CUST002',
    name_en: 'Beta Traders',
    name_ar: 'بيتا للتجار',
    vat_number: '1000000002',
    cr_number: '20000002',
    contact_person: 'Jane Smith',
    phone_number: '+966500000002',
    email: 'jane.smith@betatraders.com',
    route_days: 'Tuesday',
    building_en: 'Building B',
    building_ar: null,
    secondary_en: 'Suite 102',
    secondary_ar: null,
    street_en: 'Olaya Street',
    street_ar: null,
    district_en: 'Al Malaz',
    district_ar: null,
    city_en: 'Riyadh',
    city_ar: 'الرياض',
    postal_en: '10002',
    postal_ar: null
  },
  {
    id: 'CUST003',
    name_en: 'Gamma Wholesale',
    name_ar: 'جاما للتجزئة',
    vat_number: '1000000003',
    cr_number: '20000003',
    contact_person: 'Ahmed Ali',
    phone_number: '+966500000003',
    email: 'ahmed.ali@gammawholesale.com',
    route_days: 'Wednesday',
    building_en: 'Building C',
    building_ar: null,
    secondary_en: 'Suite 103',
    secondary_ar: null,
    street_en: 'Tahlia Street',
    street_ar: null,
    district_en: 'Al Murabba',
    district_ar: null,
    city_en: 'Riyadh',
    city_ar: 'الرياض',
    postal_en: '10003',
    postal_ar: null
  },
  {
    id: 'CUST004',
    name_en: 'Delta Goods',
    name_ar: 'دلتا للسلع',
    vat_number: '1000000004',
    cr_number: '20000004',
    contact_person: 'Fatimah Hassan',
    phone_number: '+966500000004',
    email: 'fatimah.hassan@deltagoods.com',
    route_days: 'Thursday',
    building_en: 'Building D',
    building_ar: null,
    secondary_en: 'Suite 104',
    secondary_ar: null,
    street_en: 'Prince Mohammed Road',
    street_ar: null,
    district_en: 'Al Nakheel',
    district_ar: null,
    city_en: 'Riyadh',
    city_ar: 'الرياض',
    postal_en: '10004',
    postal_ar: null
  },
  {
    id: 'CUST005',
    name_en: 'Epsilon Retail',
    name_ar: 'إبسلون للبيع',
    vat_number: '1000000005',
    cr_number: '20000005',
    contact_person: 'Omar Khalid',
    phone_number: '+966500000005',
    email: 'omar.khalid@epsilonretail.com',
    route_days: 'Friday',
    building_en: 'Building E',
    building_ar: null,
    secondary_en: 'Suite 105',
    secondary_ar: null,
    street_en: 'Zahran Street',
    street_ar: null,
    district_en: 'Al Shifa',
    district_ar: null,
    city_en: 'Riyadh',
    city_ar: 'الرياض',
    postal_en: '10005',
    postal_ar: null
  },
  {
    id: 'CUST006',
    name_en: 'Zeta Distributors',
    name_ar: 'زيتا للتوزيع',
    vat_number: '1000000006',
    cr_number: '20000006',
    contact_person: 'Sara Mohammed',
    phone_number: '+966500000006',
    email: 'sara.mohammed@zetadistributors.com',
    route_days: 'Monday',
    building_en: 'Building F',
    building_ar: null,
    secondary_en: 'Suite 106',
    secondary_ar: null,
    street_en: 'King Fahd Road',
    street_ar: null,
    district_en: 'Al Olaya',
    district_ar: null,
    city_en: 'Riyadh',
    city_ar: 'الرياض',
    postal_en: '10006',
    postal_ar: null
  },
  {
    id: 'CUST007',
    name_en: 'Eta Imports',
    name_ar: 'إيتا للاستيراد',
    vat_number: '1000000007',
    cr_number: '20000007',
    contact_person: 'Yousef Ibrahim',
    phone_number: '+966500000007',
    email: 'yousef.ibrahim@etaimports.com',
    route_days: 'Tuesday',
    building_en: 'Building G',
    building_ar: null,
    secondary_en: 'Suite 107',
    secondary_ar: null,
    street_en: 'Olaya Street',
    street_ar: null,
    district_en: 'Al Malaz',
    district_ar: null,
    city_en: 'Riyadh',
    city_ar: 'الرياض',
    postal_en: '10007',
    postal_ar: null
  },
  {
    id: 'CUST008',
    name_en: 'Theta Exports',
    name_ar: 'ثيتا للتصدير',
    vat_number: '1000000008',
    cr_number: '20000008',
    contact_person: 'Laila Abdullah',
    phone_number: '+966500000008',
    email: 'laila.abdullah@thetaexports.com',
    route_days: 'Wednesday',
    building_en: 'Building H',
    building_ar: null,
    secondary_en: 'Suite 108',
    secondary_ar: null,
    street_en: 'Tahlia Street',
    street_ar: null,
    district_en: 'Al Murabba',
    district_ar: null,
    city_en: 'Riyadh',
    city_ar: 'الرياض',
    postal_en: '10008',
    postal_ar: null
  },
  {
    id: 'CUST009',
    name_en: 'Iota Products',
    name_ar: 'يُوتا للمنتجات',
    vat_number: '1000000009',
    cr_number: '20000009',
    contact_person: 'Mohammed Saleh',
    phone_number: '+966500000009',
    email: 'mohammed.saleh@iotaproducts.com',
    route_days: 'Thursday',
    building_en: 'Building I',
    building_ar: null,
    secondary_en: 'Suite 109',
    secondary_ar: null,
    street_en: 'Prince Mohammed Road',
    street_ar: null,
    district_en: 'Al Nakheel',
    district_ar: null,
    city_en: 'Riyadh',
    city_ar: 'الرياض',
    postal_en: '10009',
    postal_ar: null
  },
  {
    id: 'CUST010',
    name_en: 'Kappa Merchants',
    name_ar: 'كابا للتجار',
    vat_number: '1000000010',
    cr_number: '20000010',
    contact_person: 'Aisha Saeed',
    phone_number: '+966500000010',
    email: 'aisha.saeed@kappamerchants.com',
    route_days: 'Friday',
    building_en: 'Building J',
    building_ar: null,
    secondary_en: 'Suite 110',
    secondary_ar: null,
    street_en: 'Zahran Street',
    street_ar: null,
    district_en: 'Al Shifa',
    district_ar: null,
    city_en: 'Riyadh',
    city_ar: 'الرياض',
    postal_en: '10010',
    postal_ar: null
  },
  {
    id: 'CUST011',
    name_en: 'Lambda Ventures',
    name_ar: 'لامبدا للمشاريع',
    vat_number: '1000000011',
    cr_number: '20000011',
    contact_person: 'Hassan Yusuf',
    phone_number: '+966500000011',
    email: 'hassan.yusuf@lambdaventures.com',
    route_days: 'Monday',
    building_en: 'Building K',
    building_ar: null,
    secondary_en: 'Suite 111',
    secondary_ar: null,
    street_en: 'King Fahd Road',
    street_ar: null,
    district_en: 'Al Olaya',
    district_ar: null,
    city_en: 'Riyadh',
    city_ar: 'الرياض',
    postal_en: '10011',
    postal_ar: null
  },
  {
    id: 'CUST012',
    name_en: 'Mu Enterprises',
    name_ar: 'مو للمشاريع',
    vat_number: '1000000012',
    cr_number: '20000012',
    contact_person: 'Mariam Noor',
    phone_number: '+966500000012',
    email: 'mariam.noor@muenterprises.com',
    route_days: 'Tuesday',
    building_en: 'Building L',
    building_ar: null,
    secondary_en: 'Suite 112',
    secondary_ar: null,
    street_en: 'Olaya Street',
    street_ar: null,
    district_en: 'Al Malaz',
    district_ar: null,
    city_en: 'Riyadh',
    city_ar: 'الرياض',
    postal_en: '10012',
    postal_ar: null
  },
  {
    id: 'CUST013',
    name_en: 'Nu Stores',
    name_ar: 'نو للمتاجر',
    vat_number: '1000000013',
    cr_number: '20000013',
    contact_person: 'Khalid Faisal',
    phone_number: '+966500000013',
    email: 'khalid.faisal@nustores.com',
    route_days: 'Wednesday',
    building_en: 'Building M',
    building_ar: null,
    secondary_en: 'Suite 113',
    secondary_ar: null,
    street_en: 'Tahlia Street',
    street_ar: null,
    district_en: 'Al Murabba',
    district_ar: null,
    city_en: 'Riyadh',
    city_ar: 'الرياض',
    postal_en: '10013',
    postal_ar: null
  },
  {
    id: 'CUST014',
    name_en: 'Xi Markets',
    name_ar: 'زاي للأسواق',
    vat_number: '1000000014',
    cr_number: '20000014',
    contact_person: 'Noura Saif',
    phone_number: '+966500000014',
    email: 'noura.saif@ximarkets.com',
    route_days: 'Thursday',
    building_en: 'Building N',
    building_ar: null,
    secondary_en: 'Suite 114',
    secondary_ar: null,
    street_en: 'Prince Mohammed Road',
    street_ar: null,
    district_en: 'Al Nakheel',
    district_ar: null,
    city_en: 'Riyadh',
    city_ar: 'الرياض',
    postal_en: '10014',
    postal_ar: null
  },
  {
    id: 'CUST015',
    name_en: 'Omicron Services',
    name_ar: 'أوميكرون للخدمات',
    vat_number: '1000000015',
    cr_number: '20000015',
    contact_person: 'Saud Sultan',
    phone_number: '+966500000015',
    email: 'saud.sultan@omicronservices.com',
    route_days: 'Friday',
    building_en: 'Building O',
    building_ar: null,
    secondary_en: 'Suite 115',
    secondary_ar: null,
    street_en: 'Zahran Street',
    street_ar: null,
    district_en: 'Al Shifa',
    district_ar: null,
    city_en: 'Riyadh',
    city_ar: 'الرياض',
    postal_en: '10015',
    postal_ar: null
  },
  {
    id: 'CUST016',
    name_en: 'Pi Logistics',
    name_ar: 'باي للنقل',
    vat_number: '1000000016',
    cr_number: '20000016',
    contact_person: 'Huda Zain',
    phone_number: '+966500000016',
    email: 'huda.zain@pilogistics.com',
    route_days: 'Monday',
    building_en: 'Building P',
    building_ar: null,
    secondary_en: 'Suite 116',
    secondary_ar: null,
    street_en: 'King Fahd Road',
    street_ar: null,
    district_en: 'Al Olaya',
    district_ar: null,
    city_en: 'Riyadh',
    city_ar: 'الرياض',
    postal_en: '10016',
    postal_ar: null
  },
  {
    id: 'CUST017',
    name_en: 'Rho Solutions',
    name_ar: 'رو للحلول',
    vat_number: '1000000017',
    cr_number: '20000017',
    contact_person: 'Talal Majid',
    phone_number: '+966500000017',
    email: 'talal.majid@rhosolutions.com',
    route_days: 'Tuesday',
    building_en: 'Building Q',
    building_ar: null,
    secondary_en: 'Suite 117',
    secondary_ar: null,
    street_en: 'Olaya Street',
    street_ar: null,
    district_en: 'Al Malaz',
    district_ar: null,
    city_en: 'Riyadh',
    city_ar: 'الرياض',
    postal_en: '10017',
    postal_ar: null
  },
  {
    id: 'CUST018',
    name_en: 'Sigma Supplies',
    name_ar: 'سيجما للمستلزمات',
    vat_number: '1000000018',
    cr_number: '20000018',
    contact_person: 'Noor Salim',
    phone_number: '+966500000018',
    email: 'noor.salim@sigmasupplies.com',
    route_days: 'Wednesday',
    building_en: 'Building R',
    building_ar: null,
    secondary_en: 'Suite 118',
    secondary_ar: null,
    street_en: 'Tahlia Street',
    street_ar: null,
    district_en: 'Al Murabba',
    district_ar: null,
    city_en: 'Riyadh',
    city_ar: 'الرياض',
    postal_en: '10018',
    postal_ar: null
  },
  {
    id: 'CUST019',
    name_en: 'Tau Traders',
    name_ar: 'تاو للتجارة',
    vat_number: '1000000019',
    cr_number: '20000019',
    contact_person: 'Majid Rashid',
    phone_number: '+966500000019',
    email: 'majid.rashid@tautraders.com',
    route_days: 'Thursday',
    building_en: 'Building S',
    building_ar: null,
    secondary_en: 'Suite 119',
    secondary_ar: null,
    street_en: 'Prince Mohammed Road',
    street_ar: null,
    district_en: 'Al Nakheel',
    district_ar: null,
    city_en: 'Riyadh',
    city_ar: 'الرياض',
    postal_en: '10019',
    postal_ar: null
  },
  {
    id: 'CUST020',
    name_en: 'Upsilon Goods',
    name_ar: 'أبسلون للسلع',
    vat_number: '1000000020',
    cr_number: '20000020',
    contact_person: 'Reem Yaqoub',
    phone_number: '+966500000020',
    email: 'reem.yaqoub@upsilongoods.com',
    route_days: 'Friday',
    building_en: 'Building T',
    building_ar: null,
    secondary_en: 'Suite 120',
    secondary_ar: null,
    street_en: 'Zahran Street',
    street_ar: null,
    district_en: 'Al Shifa',
    district_ar: null,
    city_en: 'Riyadh',
    city_ar: 'الرياض',
    postal_en: '10020',
    postal_ar: null
  }
];
